### PR TITLE
Adding an optional media prop to the image component

### PR DESCRIPTION
**Pull request by whitewaterdesign**
This will allow users to art direct with the <picture> tag.

### CODE REVIEW

**Comment by stefanoverna** [comment]
Hey Chris, I've seen the PR, but if I understand correctly the usage of the media query is the following:

```html
    <picture>
        <source media="(max-width: 600px)" srcset="flower-square.jpg">
        <source media="(max-width: 1023px)" srcset="flower-rectangle.jpg">
        <source media="(min-width: 1024px)" srcset="flower-large.jpg">
        <img src="flower-large.jpg">
    </picture>
```

So basically is a way of saying "for a certain media query, use some other image". But since the component would add the same media query to every `<source>`, and there's no way to specify a different image depending on the media query... this PR seems pretty useless as it is 😕 

Am I missing something here?

**Comment by whitewaterdesign** [comment]
Hi Stefano,

Yes this is correct, but a single media request is still very useful on this component.  Am currently running of the GitHub fork.  Please see my current use case:

`   <datocms-image
	v-if="portraitResponsiveImage"
	:data="portraitResponsiveImage"
	:media="'(max-width:1023px)'"
	class="asymCta__portrait"
/>`

which returns:

`<picture>
	<source
		srcset="https://www.datocms-assets.com/picture.png?ar=0.87%3A1&amp;auto=format&amp;dpr=0.25&amp;fit=crop&amp;fm=webp 215w..."
		sizes="(max-width: 863px) 100vw, 863px" media="(max-width:1023px)" type="image/webp">
	<source
		srcset="https://www.datocms-assets.com/picture.png?ar=0.87%3A1&amp;auto=format&amp;dpr=0.25&amp;fit=crop&amp;fm=webp 215w..."
		sizes="(max-width: 863px) 100vw, 863px" media="(max-width:1023px)">
	
</picture>`

So my use case...I have two differently cropped images brought through on GraphQL request and need to switch between device version (using standard responsiveImage for this) and desktop version (which is pulled through on src).

**Comment by stefanoverna** [comment]
Sorry the fact that the HTML snippet you attached is not complete does not help 😆  If we add a `media` prop we get something like this:

```
<picture>
  <source media="(max-width: 600px)" srcset="https://www.datocms-assets/XXX.png">
  <img src="https://www.datocms-assets/XXX.png">
</picture>
```

That is, we have the same image both for the `src` attribute of the `img` tag, and the`source` tags. How is that `media` attribute helping?

**Comment by whitewaterdesign** [comment]
```
 <picture>
     <source media="(max-width: 600px)" srcset="https://www.datocms-assets/XXX.png">
         <img src="https://www.datocms-assets/XYZ.png">
 </picture>
```
if you portraitResponsiveImage.src = 'https://www.datocms-assets/XYZ.png'

**Comment by stefanoverna** [comment]
Ah, so you're tweaking the payload! 

I'd rather handle this case better by passing an array of objects to `:data`:

```
[
  {
     ...desktopResponsiveImage,
     media: '(min-width:1024px)',
  },
  {
     ...portraitResponsiveImage,
     media: '(max-width:1023px)',
  }
]
```

what do you think? Seams cleaner (and more generic) to me!

**Comment by whitewaterdesign** [comment]
Ideal!

**Pull request closed without merging**
